### ISSUE TITLE
Remove defaults part in install routes

### ISSUE THREAD

**Issue by Nekith** [RocknRoot/strayFw#22]
Handle everything in the routes part.

ex :

```
blog:
  app: blog
  subdomain: blog
admin:
  app: admin
  url: /admin
home:
  app: home
```
